kind: Job
apiVersion: batch/v1
metadata:
 name: demo-job
 namespace: nginx
spec:
 completions: 1
 parallelism: 1
 template:
  metadata:
   name: demo-job-pod
   labels:
    app: batch-task
  spec:
   containers:
   - name: batch-container
     image: busybox:latest
     command: ["sh","-c", "echo Hello! && sleep 10"]
   restart: Never

# busybox just runs command

# TO RUN:  kubectl apply -f job.yml
# TO SEE jobs:  kubectl get job -n nginx 
# TO SEE RESULTS: kubectl logs -n nginx -l app=batch-task
